#ifndef  MATERIAL_HEADER_HLSL
#define  MATERIAL_HEADER_HLSL

#define MATERIAL_ATTRIBUTE_ALBEDO 0;
#define MATERIAL_ATTRIBUTE_ROUGHNESS 1;
#define MATERIAL_ATTRIBUTE_METALLIC 2;
#define MATERIAL_ATTRIBUTE_NORMAL 3;
#define MATERIAL_ATTRIBUTE_AO 4;

#define MATERIAL_ATTRIBUTE_COUNT 5

#define MATERIAL_VALUE_TYPE_SCALAR 0
#define MATERIAL_VALUE_TYPE_VEC2 1
#define MATERIAL_VALUE_TYPE_VEC3 2
#define MATERIAL_VALUE_TYPE_VEC4 3
#define MATERIAL_VALUE_TYPE_TEXTURE_SAMPLE 4

cbuffer MaterialBuffer : register(MATERIAL_BINDING, MATERIAL_SET)
{
    uint MaterialValueType0;
    uint MaterialValueType1;
    uint Pad[4];
    uint MaterialId;
    float4 MaterialData[MATERIAL_ATTRIBUTE_COUNT];
};

#endif // MATERIAL_HEADER_HLSL