#version 450


layout(set = 0, binding = 0, rgba8) uniform image2D hdrImage;

layout (local_size_x = 512, local_size_y = 1, local_size_z = 1) in;

// hardcoded for now
const float exposure = 1.f;
const float gamma = 2.2f;

// sRGB => XYZ => D65_2_D60 => AP1 => RRT_SAT
mat3 ACESInputMat = mat3(
0.59719, 0.35458, 0.04823,
0.07600, 0.90834, 0.01566,
0.02840, 0.13383, 0.83777
);

// ODT_SAT => XYZ => D60_2_D65 => sRGB
mat3 ACESOutputMat = mat3(
1.60475, -0.53108, -0.07367,
-0.10208,  1.10813, -0.00605,
-0.00327, -0.07276,  1.07602
);
vec3 RRTAndODTFit(vec3 v)
{
    vec3 a = v * (v + 0.0245786f) - 0.000090537f;
    vec3 b = v * (0.983729f * v + 0.4329510f) + 0.238081f;
    return a / b;
}


void main()
{
    uvec2 gid = gl_GlobalInvocationID.xy; // absolute pixel coordinate
    ivec2 size = imageSize(hdrImage);

    if (gid.x >= size.x || gid.y >= size.y)
        return;
    
    vec4 hdr = exposure * imageLoad(hdrImage, ivec2(gid));
    
    // aces transformation
    vec3 color = ACESInputMat * hdr.rgb;
    color = ACESOutputMat * color;
    
    color = pow(color, vec3(1.0 / gamma));
    color = clamp(color, 0.0, 1.0);

    imageStore(hdrImage, ivec2(gid), vec4(color, hdr.a));
}